# Generated by Django 5.2.16 on 2026-09-10 08:01

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название темы')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(upload_to=blog.models.post_upload_path, verbose_name='Картинка-обложка (превью и заголовок)')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('commands', models.TextField(blank=True, help_text="Будут отображены в блоке <pre class='cmd'>. Разделяйте блоки строкой из ---", verbose_name='Команды')),
                ('body', models.TextField(blank=True, help_text='Поддерживается перенос строк и вставка картинок. Чтобы вставить картинку — загрузите её ниже и вставьте плейсхолдер [[img:ID]] в нужное место.', verbose_name='Текст статьи')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.inline_image_upload_path, verbose_name='Картинка')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Картинка в статье',
                'verbose_name_plural': 'Картинки в статье',
            },
        ),
    ]
