# Generated by Django 5.2.16 on 2026-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('code', models.TextField(help_text='Можно несколько строк, переносы сохранятся.', verbose_name='Команда')),
                ('description', models.TextField(blank=True, help_text='Что делает команда, зачем, какие нюансы.', verbose_name='Описание')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands_list', to='blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды (с описанием)',
                'ordering': ('order', 'id'),
            },
        ),
    ]
