# Generated by Django 5.2.16 on 2026-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='Открывается в визуальном редакторе: заголовки, курсив, ссылки, картинки. Старый способ тоже работает: загрузите картинку ниже и вставьте плейсхолдер [[img:ID]] в нужное место.', verbose_name='Текст статьи'),
        ),
    ]
